### ISSUE TITLE
Login and Sign up 

### ISSUE THREAD

**Issue by yu-zha** [COSC481W-2021Fall/capstone-snack-attack#23]
### Acceptance Criteria

- [x] If the user fills in the correct username and password, then clicks the sign in button, the user should be logged in and redirected to the home page if a customer account or redirected to the manage store page if a store manager account.
- [x] If the user fills in an incorrect username and password, then clicks the sign in button, the user will not be logged in, will stay on the sign-in page, and will see a warning.
- [x] If the user leaves the username or password blank, then clicks the sign in button, the user will stay on the sign-in page and see a warning.
- [ ] If the user clicks the sign up button, the user will be redirected to the sign up page.
- [x] The user must enter a unique username, password, email, first name, last name, and select either a customer account or store manager account. If all of these are filled in and the user clicks the sign-up button, the user's account will be created and the user will be redirected to the sign-in page.
- [ ] If the user's entered username is not unique, the user will stay on the sign-up page and see a warning.
- [x] If any of the sign-up fields are missing, the user will stay on the sign-up page and see a warning.
- [ ] Passwords must be hashed for security.
- [x] Passwords must have a minimum of 8 characters and contain at least one letter and one number.

### Tasks

- [x] Database for the username/password, for customer and store manager. (Sandra)
- [x] On the backend, check if the user's credentials are valid. (Sandra)
- [x] On the backend, handle the case where the user is authorized to log in. (Sandra)
- [ ] On the backend, handle the case where the user is not authorized. (Alex)
- [ ] On the frontend, create a webpage for users to sign in. (Kulwinder)
- [ ] On the frontend, create the username textbox, create the password textbox, create the sign in button. (Kulwinder)
- [ ] On the frontend, add the warning messages if the username or the password is left blank when the sign in button is clicked. (Kulwinder)
- [ ] On the frontend, add the warning message if the username and the password are not valid. (Kulwinder)
- [ ] Testing and deploying (all)
- [ ] On the backend, handle the case where the user is authorized to sign up for an account. (Alex)
- [ ] On the backend, handle the case where the user is not authorized to sign up for an account. (Alex)
- [x] On the frontend, create a sign-up webpage to create a new account. (Ke)
- [x] On the frontend, add the textboxes for username, password for store manager accounts. (Ke)
- [x] On the frontend, add the warning where the username is not unique. (Ke)
- [x] On the frontend, add the warning where any of the fields are missing.  (Ke)
- [x] On the front end, add the warning where the password does not satisfy the requirements. (Ke)
- [x] On the frontend, add the textboxes for username, password, first name, last name, and email for customer accounts.(Ke, may complete it later)
- [x] On the frontend, create a home page where redirects to signup pages. (Ke)
- [x] Connect signup websites to backend. (Ke)
- [ ] Connect login website to backend. ()

**Comment by sjiang1** [comment]
Please add another acceptance criterion:
The password should have a basic requirement, such as a minimum length of 8 chars, etc.

**Comment by London-Alex** [comment]
Acceptance criteria has been updated.

**Comment by SuperRedTrain** [comment]
Add a task: On the front end, add the warning where the password does not satisfy the requirements.
