### ISSUE TITLE
Add new products

### ISSUE THREAD

**Issue by yu-zha** [COSC481W-2021Fall/capstone-snack-attack#25]
### Acceptance Criteria

- [ ] If the store manager fills the correct title, price, description, quantity, category and upload the pictures successfully, then click the ADD button. The new product will add to the store successfully, and customer can see it.
- [ ] If the store manager fills any mistake information, after click ADD button, the web will prompt a warning message.
- [x] If the user is logged in as a store manager, they are able to access the Add Product page. If the user is not logged in as a store manager, they should not be able to see or access the Add Product page.
- [ ] If the store already has an item with the same name, the item will not be added and the user will see a warning message.
- [ ] If the item has a quantity of less than 1, the item will not be added and the user will see a warning message.

### Task

- [ ] Setup MongoDB Atlas Database and add each item of the online shop, with its corresponding category. (YU)
- [ ] On the frontend, create the admin panel for store manager to manage their stores.  (Kulwinder)
- [ ] On the backend, verify that the user is able to access the Add Product page. (Alex)
- [ ] On the backend, verify that the item is able to be added. (not a duplicate, all fields filled, quantity > 0) (Alex)
- [ ] On the backend, handle the case where the item is able to be added to the database and website. (Alex)
- [ ] On the backend, handle the case where the item is not able to be added to the database and website. (Yu)
- [x] On the frontend, create the Add Product page. (Sandra)
- [x] On the frontend, create the input boxes for the Add Product page (title, price, description, quantity, category. (Sandra)
- [ ] On the frontend, create the input for adding pictures to the item. ()
- [ ] On the frontend, create the warning messages if the fields are not filled in. ()
- [ ] On the frontend, create the warning message if the item is a duplicate. ()
- [ ] On the frontend, create the warning message if the quantity is less than 1. ()
