### ISSUE TITLE
Fix bugs for Login and Sign up

### ISSUE THREAD

**Issue by SuperRedTrain** [COSC481W-2021Fall/capstone-snack-attack#40]
**Acceptance Criteria**
- [x] Make sure Login and Sign up function work

**Tasks**
- [x] Modify codes on the backend to make sure the backend can work with the frontend
- [x] Delete duplicated functions on the backend
- [x] Modify codes on the frontend to make Login connect to the backend
- [x] Modify codes on the frontend to make Login and Sign up work together
- [x] Delete duplicated functions on the frontend
- [x] Delete unused folders and combine folders to make layout clear
