### ISSUE TITLE
Add Store Manager Panel

### ISSUE THREAD

**Issue by yu-zha** [COSC481W-2021Fall/capstone-snack-attack#45]
**Acceptance Criteria**

- [x] As a store manager I want to redirect to store manager's dropdown menu after the store manager login successfully.
- [x] As a store manager, I want to log out of my account.
- [x] The Add Product button redirects the store manager to the Add Product page.

**Task**

- [x] Create a dropdown menu for store manager. (Ke, Yu)
- [x] Connect the feature with the "Add Product" button  (Kulwinder, Yu)
- [x] Add the logout feature.(Ke, Yu)
- [x] Show the store manager's dropdown menu after store manager login successfully. (Ke)
