### ISSUE TITLE
Create Shipping Address Page

### ISSUE THREAD

**Issue by yu-zha** [COSC481W-2021Fall/capstone-snack-attack#59]
**Acceptance Criteria**
- [x] When the user has clicked the checkout button from the cart, then they will redirect to the shipping info page. This page has several text-input spaces like: Name, Address, City, State, Zipcode
- [x] If there is an error in any of the information entered, an error message will be displayed.
- [x] After the user fills in this information correctly, then clicking the continue button, it will redirect to the bill info page. (This page will be created in the next sprint)

**Tasks**
- [x] Create a shipping screen, with Name, Address, City, State, Zipcode text input spaces for the user.
- [x] Check the validation of all the information that the user entered.
- [x] Create a "Continue" button to access the payment page.
- [x] Add CART_SAVE_SHIPPING_ADDRESS to cartReducers
